with open('app/src/main/java/com/example/ui/screens/AlgoScreen.kt', 'r') as f:
    content = f.read()

content = content.replace("screensimport", "screens\nimport")
content = content.replace("Historyimport", "History\nimport")
content = content.replace("Canvasimport", "Canvas\nimport")
content = content.replace("backgroundimport", "background\nimport")
content = content.replace("borderimport", "border\nimport")
content = content.replace("clickableimport", "clickable\nimport")
content = content.replace("layout.*import", "layout.*\nimport")
content = content.replace("LazyColumnimport", "LazyColumn\nimport")
content = content.replace("itemsimport", "items\nimport")
content = content.replace("Stateimport", "State\nimport")
content = content.replace("CircleShapeimport", "CircleShape\nimport")
content = content.replace("CornerShapeimport", "CornerShape\nimport")
content = content.replace("verticalScrollimport", "verticalScroll\nimport")
content = content.replace("Iconsimport", "Icons\nimport")
content = content.replace("ArrowBackimport", "ArrowBack\nimport")
content = content.replace("Addimport", "Add\nimport")
content = content.replace("FilterListimport", "FilterList\nimport")
content = content.replace("outlined.*import", "outlined.*\nimport")
content = content.replace("material3.*import", "material3.*\nimport")
content = content.replace("runtime.*import", "runtime.*\nimport")
content = content.replace("Alignmentimport", "Alignment\nimport")
content = content.replace("Modifierimport", "Modifier\nimport")
content = content.replace("Offsetimport", "Offset\nimport")
content = content.replace("Colorimport", "Color\nimport")
content = content.replace("Pathimport", "Path\nimport")
content = content.replace("Strokeimport", "Stroke\nimport")
content = content.replace("FontWeightimport", "FontWeight\nimport")
content = content.replace("TextAlignimport", "TextAlign\nimport")
content = content.replace("dpimport", "dp\nimport")
content = content.replace("spimport", "sp\nimport")
content = content.replace("Strategyimport", "Strategy\nimport")
content = content.replace("CrownLogoimport", "CrownLogo\nimport")
content = content.replace("theme.*import", "theme.*\nimport")
content = content.replace("AlgoEngineimport", "AlgoEngine\nimport")
content = content.replace("MainViewModelval", "MainViewModel\n\nval")

with open('app/src/main/java/com/example/ui/screens/AlgoScreen.kt', 'w') as f:
    f.write(content)
