import re

with open("app/src/main/java/com/example/ui/components/BrokerConnectDialog.kt", "r") as f:
    content = f.read()

# Upstox
content = content.replace('Text(\n                                "Upstox (Primary Market Data)",\n                                color = TextWhite,\n                                fontSize = 15.sp,\n                                fontWeight = FontWeight.Bold\n                            )\n                        }\n                        Spacer(modifier = Modifier.height(12.dp))', 
'Text(\n                                "Upstox (Primary Market Data)",\n                                color = TextWhite,\n                                fontSize = 15.sp,\n                                fontWeight = FontWeight.Bold\n                            )\n                        }\n                        Spacer(modifier = Modifier.height(16.dp))\n                        BrokerDiagnosticPanel(selectedBroker, brokerStatuses[selectedBroker], providerHealth[selectedBroker], { onDisconnect?.invoke(selectedBroker) }, { onReconnect?.invoke(selectedBroker) })\n                        Spacer(modifier = Modifier.height(16.dp))')

# m.Stock
content = content.replace('Text(\n                                "m.Stock (Fallback #2 Market Data)",\n                                color = TextWhite,\n                                fontSize = 15.sp,\n                                fontWeight = FontWeight.Bold\n                            )\n                        }\n                        Spacer(modifier = Modifier.height(16.dp))',
'Text(\n                                "m.Stock (Fallback #2 Market Data)",\n                                color = TextWhite,\n                                fontSize = 15.sp,\n                                fontWeight = FontWeight.Bold\n                            )\n                        }\n                        Spacer(modifier = Modifier.height(16.dp))\n                        BrokerDiagnosticPanel(selectedBroker, brokerStatuses[selectedBroker], providerHealth[selectedBroker], { onDisconnect?.invoke(selectedBroker) }, { onReconnect?.invoke(selectedBroker) })\n                        Spacer(modifier = Modifier.height(16.dp))')

# Fyers
content = content.replace('Text(\n                                "Fyers (Alternative Market Data)",\n                                color = TextWhite,\n                                fontSize = 15.sp,\n                                fontWeight = FontWeight.Bold\n                            )\n                        }\n                        Spacer(modifier = Modifier.height(12.dp))',
'Text(\n                                "Fyers (Alternative Market Data)",\n                                color = TextWhite,\n                                fontSize = 15.sp,\n                                fontWeight = FontWeight.Bold\n                            )\n                        }\n                        Spacer(modifier = Modifier.height(16.dp))\n                        BrokerDiagnosticPanel(selectedBroker, brokerStatuses[selectedBroker], providerHealth[selectedBroker], { onDisconnect?.invoke(selectedBroker) }, { onReconnect?.invoke(selectedBroker) })\n                        Spacer(modifier = Modifier.height(16.dp))')

# Angel One
content = content.replace('Text(\n                                "Angel One (Fallback #1 Market Data)",\n                                color = TextWhite,\n                                fontSize = 15.sp,\n                                fontWeight = FontWeight.Bold\n                            )\n                        }\n                        Spacer(modifier = Modifier.height(16.dp))',
'Text(\n                                "Angel One (Fallback #1 Market Data)",\n                                color = TextWhite,\n                                fontSize = 15.sp,\n                                fontWeight = FontWeight.Bold\n                            )\n                        }\n                        Spacer(modifier = Modifier.height(16.dp))\n                        BrokerDiagnosticPanel(selectedBroker, brokerStatuses[selectedBroker], providerHealth[selectedBroker], { onDisconnect?.invoke(selectedBroker) }, { onReconnect?.invoke(selectedBroker) })\n                        Spacer(modifier = Modifier.height(16.dp))')

# Dhan
content = content.replace('Text(\n                                "Dhan (Order Execution)",\n                                color = TextWhite,\n                                fontSize = 15.sp,\n                                fontWeight = FontWeight.Bold\n                            )\n                        }\n                        Spacer(modifier = Modifier.height(12.dp))',
'Text(\n                                "Dhan (Order Execution)",\n                                color = TextWhite,\n                                fontSize = 15.sp,\n                                fontWeight = FontWeight.Bold\n                            )\n                        }\n                        Spacer(modifier = Modifier.height(16.dp))\n                        BrokerDiagnosticPanel(selectedBroker, brokerStatuses[selectedBroker], providerHealth[selectedBroker], { onDisconnect?.invoke(selectedBroker) }, { onReconnect?.invoke(selectedBroker) })\n                        Spacer(modifier = Modifier.height(16.dp))')

with open("app/src/main/java/com/example/ui/components/BrokerConnectDialog.kt", "w") as f:
    f.write(content)
